language: node_js
node_js:
  - "12"
install:
  - yarn --pure-lockfile
script:
  - yarn build
  - yarn test
  - yarn benchmark
deploy:
  provider: npm
  email: v.mladenov@hotmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true  # skip cleanup- if yarn build was forgotten.
  on:
    tags: true
